config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get '/secret_page', to: 'static_pages#secret_page'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources 'users'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	
  # before_save   self.email = email.downcase

  VALID_EMAIL_REGEX  =  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  
  validates :password,  presence: true, length: { minimum: 6 }

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params_session[:email].downcase)
    if user && user.authenticate(params_session[:password])
      log_in user
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to '/login'
  end

  private

  def params_session
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	
  def home
  end

  def secret_page
    if !logged_in?
      flash[:danger] = 'Faut être loggé pour aller sur la page secrète !!!'
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params_user)
      p "------------------------------------------------------"
      p @user.errors
      p @user.errors.messages
    if @user.save
      log_in @user
      redirect_to root_path
    else
     p "------------------------------------------------------"
      p @user.errors
      p @user.errors.messages

      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      flash[:danger] = 'You cannot edit someone else than yourself'
      redirect_to users_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(params_user)
      redirect_to users_path
    else
      render 'edit'
    end
  end

  private

  def params_user
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="/">Youpi</a>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">Index</a>
      </li>
      <li class="nav-item">
        <%= puts logged_in? %>
        <%= if logged_in?
          link_to "Logout", '/logout', method: :delete, class: "nav-link", data: { confirm: "T'es sûr de toi ?" }
        else
          link_to "Login", '/login', class: "nav-link"
        end %>
      </li>
      <li class="nav-item">
        <%= link_to "Users", users_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reponsedelunivers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container" style="padding-top: 5rem;">
      <% if flash[:danger] %>
        <div class="alert alert-danger">
          <%= flash[:danger] %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>Bienvenue sur notre page</h1>
<p> Nous allons pouvoir répondre à la question de l'univers</p>

<% if logged_in? %>
  <p><a href='<%= secret_page_path %>'>Suivez-nous!</a></p>
<% end %>

app/views/static_pages/secret_page.html.erb
<h1>This is a secret page!</h1>

app/views/users/edit.html.erb
<h1>Votre profil</h1>

<%= form_for :user, url: user_path, method: :patch do |f| %>
  Email: <%= f.text_field :email %><br/>
  Password: <%= f.text_field :password %><br/>
  Password confirmation: <%= f.text_field :password_confirmation %><br/>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<table class="table">
  <thead class="thead-light">
    <tr>
      <th>id</th>
      <th>email</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, edit_user_path(user) %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= button_to 'new!', new_user_path, method: :get, class: "btn btn-default" %>

app/views/users/new.html.erb
<h1>Bienvenue sur ton profil</h1>
<p>Connecte toi pour pouvoir découvrir la reponse de l'univers</p>

<%= form_for :user, url: users_path do |f| %>
  Email: <%= f.text_field :email %><br/>
  Mot de passe: <%= f.text_field :password %><br/>
  Confirmation du mot de passe: <%= f.text_field :password_confirmation %><br/>
  <br/>
  <%= f.submit %>
<% end %>